name: Docker Publish

# 触发条件：每当推送到 main 分支时触发
on:
  push:
    branches:
      - main

# 工作流的定义
jobs:
  build:
    runs-on: archlinux-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Docker 环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 从 GitHub Secrets 中获取 Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 从 GitHub Secrets 中获取 Docker Hub 密码

      # 构建 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # 指定 Dockerfile 和上下文路径
          push: true  # 设置为 true 表示构建后推送镜像到 Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/liuyan:${{ github.sha }}  # 为镜像添加标签，使用 commit 的 sha 作为标签

      # 可选：可以进行其他操作，比如清理工作
      - name: Logout from Docker Hub
        run: docker logout
